/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppTable: typeof import('./src/components/AppTable.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
